---
- name: Restart prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: Reload systemd
  ansible.builtin.command:
    argv: ["systemctl", "daemon-reload"]
  changed_when: true

- name: Restart alertmanager
  ansible.builtin.service:
    name: prometheus-alertmanager
    state: restarted
