---
- name: Restart prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: Restart alertmanager
  ansible.builtin.service:
    name: prometheus-alertmanager
    state: restarted
