---
- name: Ensure Prometheus + Alertmanager are installed
  ansible.builtin.apt:
    name:
      - prometheus
      - prometheus-alertmanager
    state: present
    update_cache: true

- name: Install Prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: "0644"
  notify: Restart prometheus

- name: Install Alertmanager configuration
  ansible.builtin.template:
    src: alertmanager.yml.j2
    dest: /etc/prometheus/alertmanager.yml
    owner: root
    group: root
    mode: "0644"
  notify: Restart alertmanager

- name: Ensure Prometheus is enabled and started
  ansible.builtin.service:
    name: prometheus
    enabled: true
    state: started

- name: Ensure Alertmanager is enabled and started
  ansible.builtin.service:
    name: prometheus-alertmanager
    enabled: true
    state: started
