---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart etcd
  ansible.builtin.service:
    name: etcd
    state: restarted

- name: Restart Patroni
  ansible.builtin.service:
    name: "{{ postgres_patroni_service_name }}"
    state: restarted
