---
- name: Restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted

- name: Restart keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted

- name: Restart nftables
  ansible.builtin.service:
    name: nftables
    state: restarted

- name: Update CA certificates
  ansible.builtin.command: update-ca-certificates
  register: minio_edge_lb_ca_update
  changed_when: "'0 added' not in minio_edge_lb_ca_update.stdout"
